### ISSUE TITLE
sqljs usage changes

### ISSUE THREAD

**Issue by linonetwo** [citycide/trilogy#96] opened 2019-05-13 10:12 UTC
https://github.com/citycide/trilogy/blob/506126c4f4e626a36c48f0d2cf50c34bea07c66c/src/sqljs-handler.js#L8

https://github.com/kripken/sql.js/issues/270#issuecomment-491743275

**Comment by linonetwo** [comment] 2019-05-13 10:26
Causing https://github.com/citycide/trilogy/issues/95

**Comment by citycide** [comment] 2019-05-15 02:23
Duplicate of #95

**Closed by citycide** 2019-05-15 02:23 UTC
Labels: duplicate
