### ISSUE TITLE
Issue while using it with Angular 4 

### ISSUE THREAD

**Issue by vrbagal** [citycide/trilogy#64] opened 2017-07-25 05:08 UTC
I am trying to use Triology with [this](https://github.com/stokingerl/Angular2-Electron-Boilerplate) boilerplate , when I import trilogy in one of the TS file in src folder and run, it shows following error 

![image](https://user-images.githubusercontent.com/30340701/28556658-63636716-7125-11e7-9271-ae9b9fbb3a44.png)

**Comment by citycide** [comment] 2017-07-25 05:48
@vrbagal it's possible this is actually because of TypeScript but I'll have to look more into it.

**Comment by citycide** [comment] 2017-07-25 06:04
Also, if you have time it'd help a lot if you push up a repo I can pull down to test this out.

**Comment by vrbagal** [comment] 2017-07-25 06:32
repo :-> https://github.com/vrbagal/Angular-4-Electron-

**Comment by citycide** [comment] 2017-07-25 20:42
I pushed a fix in e1d57c3 that drops defining `module.exports` for the `.mjs` / module build.

Released in [v1.2.1](https://github.com/citycide/trilogy/releases/tag/v1.2.1)

**Closed by citycide** 2017-07-25 20:42 UTC
Labels: status: investigating

**Comment by vrbagal** [comment] 2017-07-26 05:50
Could you please add code snip to import and use it with typescript, I am not able to get it running with [this](https://github.com/vrbagal/Angular-4-Electron-) repo

**Comment by citycide** [comment] 2017-07-26 06:57
Hmm. Original issue's fixed but it looks like there's a new one ( or two ). I've been trying to track them down but it's pretty easy to get tangled in webpack's webs...

### using sql.js

`__webpack_require__.i(...) is not a function`

I'm not well versed in webpack's innards but this seems like a webpack issue. That API isn't working for some reason. I guess it could be the fact that node's `path` ( which is what's being replaced by webpack's require above ) isn't an ES module so `import`ing while in an `.mjs` module could potentially be the issue? 🤷‍♂️ 

### using sqlite3

This one I know more about than the above:

`Cannot read property 'create' of undefined`

... which I traced through knex into its usage of `generic-pool`. The problem is that we have this tree:

```shell
$ npm ls generic-pool
electron-angular-boilerplate@0.0.0 C:\......\Angular-4-Electron-
`-- trilogy@1.2.1
  +-- generic-pool@3.1.7
  `-- knex@0.13.0
    `-- generic-pool@2.5.4
```

`generic-pool` v3.0.0 ( which trilogy itself uses ) had a breaking change to its `Pool` constructor's signature. For whatever reason webpack is giving knex `generic-pool@3.1.7` when it should be getting its own `generic-pool@2.5.4` dependency. That seems pretty jacked to me. We'll probably have to open an upstream issue with webpack.
